### ISSUE TITLE
Error: Portlet could not be found

### ISSUE THREAD

**Issue by Lythenas** [eclipse/sw360#1099] opened 2021-01-26 15:53 UTC
After installing sw360 (I tried both with docker and vagrant) and adding the lar files I get "portlet could not be found" on every page.

![image](https://user-images.githubusercontent.com/32217236/105867589-8c46ab80-5ff5-11eb-817c-559971416c39.png)

I followed this guide to import the lar files: https://github.com/eclipse/sw360/wiki/Deploy-Liferay7.3

I used the same lar files as in the screenshots there: `Public_Pages_7_3_3_GA4.lar` and `Private_Pages_7_3_3_GA4.lar`.

**Comment by KoukiHama** [comment] 2021-01-29 13:51
Nowthe issue is that among the prerequisites, the commons compress is missing

https://github.com/sw360/sw360chores/pull/83#issuecomment-758264831

**Comment by mcjaeger** [comment] 2021-03-31 19:10
there has not been an update for a while, let's consider closing this.

**Closed by mcjaeger** 2021-03-31 19:10 UTC
