### ISSUE TITLE
'Show License Info' button doesn't work with spdx file export from FOSSology when there is a '+' in license name

### ISSUE THREAD

**Issue by drej** [eclipse/sw360#1129] opened 2021-03-02 07:04 UTC
RHEL 8, SW360 12.0
The spdx file exported by fossology will replace '+' with '%2B'.
The 'Show License Info' in Components - Releases - Clearing Details couldn't work fine with it, even the main license's name doesn't have a '+'.
The problem will make other spdx attachments which don't have '%2B' in it broken by chance. Unless user delete all spdx files with '%2B' the problem won't be solved.

**Comment by akapti** [comment] 2021-03-10 04:46
root cause in file: https://github.com/eclipse/sw360/blob/39f0e5ef88dadca9bbd807fe2382841cd8944147/backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTools.java#L120

**Comment by KoukiHama** [comment] 2021-03-10 05:09
I found the issue related to this.
https://github.com/eclipse/sw360/issues/656

**Comment by KoukiHama** [comment] 2021-03-10 23:26
@drej  
I checked the problem  on sw360 ver13 (commit 7091c4b64394) and didn't find this issue.
Can you share spdx file which you use?

**Comment by akapti** [comment] 2021-03-11 04:30
@KoukiHama I am able to reproduce this issue using spdx attached below: The Main License here is `GPL-2.0+`... and it's parsing fails due to `+` / `%2B` in the license.
[SPDX2_drivers.zip_1567589134-spdx.zip](https://github.com/eclipse/sw360/files/6120408/SPDX2_drivers.zip_1567589134-spdx.zip)

**Comment by KoukiHama** [comment] 2021-03-11 04:54
@akapti Thanks I checked it and  was able to reproduce.

**Comment by tienlee** [comment] 2021-03-12 03:11
I can reproduce the issue on SW360 12.0, same with @drej 's issue
> The 'Show License Info' in Components - Releases - Clearing Details couldn't work fine with it
> The problem will make other spdx attachments which don't have '%2B' in it broken by chance.

About @akapti 's issue on SW360 13.0 (included the new Parser, PR #1097 was merged), it is not effect to other SPDX attachments

FOSSology has an option called by SPDX compatible, the default value is Yes, and SPDX file will include the link to spdx.org
In my side, to avoid this issue, I change the default value to No (for the license name with + character), the SPDX license info text will get from FOSSology database, so the problem is solved without any change from SW360 source code.

In addition, if we want to fix this issue from SW360, I can think about 2 solutions:
* As my understand, the "/", "#", "+", "%2B" are split points of Util.splitNamespaceXML function. In case of get license name from URL, we will split by "/", "#" and don't use Util.splitNamespaceXML function
* Get all license ID from SW360 database, compare with URL and get the correct license. If SW360 database doesn't contain the license in URL, the result is still empty.

**Closed** 2021-03-31 11:42 UTC
Labels: bug
