### ISSUE TITLE
Core dump on sw360chores.pl  -- up

### ISSUE THREAD

**Issue by dreh23** [eclipse/sw360#442] opened 2019-01-18 14:03 UTC
Following happens sometimes without any pattern. Which information is needed to debug this?

```
sw360                  | SEVERE: Unable to process Jar entry [org/eclipse/sw360/datahandler/thrift/components/ComponentService$getReleasesByIdsForExport_result$getReleasesByIdsForExport_resultStandardSchemeFactory.class] from Jar [jar:file:/opt/sw360/webapps/attachments/WEB-INF/lib/datahandler-3.4.0-SNAPSHOT.jar!/] for annotations
sw360                  | java.util.zip.ZipException: error reading zip file
sw360                  |        at java.util.zip.ZipFile.read(Native Method)
sw360                  |        at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
sw360                  |        at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:734)
sw360                  |        at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:434)
sw360                  |        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
sw360                  |        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
sw360                  |        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
sw360                  |        at java.io.DataInputStream.readInt(DataInputStream.java:387)
sw360                  |        at org.apache.tomcat.util.bcel.classfile.ClassParser.readID(ClassParser.java:202)
sw360                  |        at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:80)
sw360                  |        at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2089)
sw360                  |        at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1965)
sw360                  |        at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1931)
sw360                  |        at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1916)
sw360                  |        at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1330)
sw360                  |        at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:889)
sw360                  |        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:386)
sw360                  |        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
sw360                  |        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
sw360                  |        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5416)
sw360                  |        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
sw360                  |        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
sw360                  |        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
sw360                  |        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
sw360                  |        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1263)
sw360                  |        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1948)
sw360                  |        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
sw360                  |        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
sw360                  |        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
sw360                  |        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
sw360                  |        at java.lang.Thread.run(Thread.java:748)
sw360                  |
sw360                  | #
sw360                  | # A fatal error has been detected by the Java Runtime Environment:
sw360                  | #
sw360                  | #  SIGBUS (0x7) at pc=0x00007fcdc8862d2c, pid=19, tid=0x00007fcdaa70aae8
sw360                  | #
sw360                  | # JRE version: OpenJDK Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
sw360                  | # Java VM: OpenJDK 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)
sw360                  | # Derivative: IcedTea 3.10.0
sw360                  | # Distribution: Custom build (Thu Jan 10 09:44:25 UTC 2019)
sw360                  | # Problematic frame:
sw360                  | # C  [libzip.so+0x4d2c]  Java_java_util_zip_ZipFile_getZipMessage+0xd7c
sw360                  | #
sw360                  | # Core dump written. Default location: /opt/sw360/core or core.19
sw360                  | #
sw360                  | # An error report file with more information is saved as:
sw360                  | # /opt/sw360/hs_err_pid19.log
sw360                  | Compiled method (nm)   68296 1218     n 0       java.util.zip.ZipFile::getNextEntry (native)
sw360                  |  total in heap  [0x00007fcdb9d69e10,0x00007fcdb9d6a168] = 856
sw360                  |  relocation     [0x00007fcdb9d69f38,0x00007fcdb9d69f80] = 72
sw360                  |  main code      [0x00007fcdb9d69f80,0x00007fcdb9d6a168] = 488
sw360                  |   Copying 1 file to /opt/sw360/webapps/attachments
sw360                  |   Deleting directory /opt/sw360/temp/20190118135601628
sw360                  | 13:56:02,182 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][PortletAutoDeployListener:91] Portlets for /opt/sw360/deploy/attachments.war copied successfully. Deployment will start in a few seconds.
sw360                  | 13:56:02,186 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:204] Processing authorization.war
sw360                  | 13:56:02,186 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][PortletAutoDeployListener:69] Deploying package asa web application
sw360                  | 13:56:02,186 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][PortletAutoDeployListener:79] Copying portlets for/opt/sw360/deploy/authorization.war
```

**Comment by maxhbr** [comment] 2019-01-23 13:50
I think the problem is, that the `attachments.war` file was not copied completely to the `_deploy` folder, before the liferay deploy scheduler started to consume the zip file. This means that a simple redeploy should fix that.

You can also recognize that this happened, if a file is remaining in the folder `_deploy`. You can enforce another try to deploy by touching the file.

Could it be fixed by redeploying?

**Comment by maxhbr** [comment] 2019-08-27 12:50
will be prevented by the new deployment mechanism in https://github.com/sw360/sw360chores/pull/65

**Comment by mcjaeger** [comment] 2020-03-05 01:13
since the PR was merged, closing here.

**Closed by mcjaeger** 2020-03-05 01:13 UTC
