### ISSUE TITLE
In generating License Info: how to Generate License Info with concluded license only

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#211] opened 2018-04-26 15:58 UTC
<a href="https://github.com/binhth1307"><img src="https://avatars1.githubusercontent.com/u/34565625?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [binhth1307](https://github.com/binhth1307)**
_Tuesday Jan 30, 2018 at 04:41 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/734_

----

Hi, 
Currently, I am using SPDX from FOSSology with the both of scanned license (LicenseInfoInFile) and concluded license (LicenseConcluded), and Generate License Info for our products require only the concluded license, but sw360 always generates a report with the both of them.
How to Generate License Info with concluded license only?

It's the same #698 issue.
Could you please help me make clear this issue?

Best regards,
BinhTH

**Comment by mcjaeger** [comment] 2018-09-22 20:37
seems to be duplicate of https://github.com/eclipse/sw360/issues/195

**Closed by mcjaeger** 2018-09-22 20:37 UTC
Labels: needs clarification, question
